tictactoe/apps/gameplay/urls.py
from django.urls import path

tictactoe/apps/main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'main'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    # url(r'^$', views.home, name='home'),
]

tictactoe/apps/player/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'player'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',
         LoginView.as_view(template_name='player/login_form.html'),
         name='player_login'),
    path('logout/',
         LogoutView.as_view(),
         name='player_logout'),
    # url(r'^$', views.home, name='home'),
]

tictactoe/tictactoe/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'tictactoe'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('apps.main.urls')),
    path('player/', include('apps.player.urls')),
]

tictactoe/apps/gameplay/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q # enables logical operators

GAME_STATUS_CHOICES = (
    ('F', 'First player to move'),
    ('S', 'Second player to move'),
    ('W', 'First player wins'),
    ('L', 'Second player wins'),
    ('D', 'Draw')
)


class GamesQuerySet(models.QuerySet):
    def games_for_user(self, user):
        # lists all games that user is in
        return self.filter(
            Q(first_player=user) | Q(second_player=user)
        )

    def active(self):
        # list all games that are still on-going
        return self.filter(
            Q(status='F') | Q(status='S')
        )

    def draw(self):
        # list all games that ended in draw
        return self.filter(Q(status='D'))


class Game(models.Model):
    first_player = models.ForeignKey(User, related_name="game_first_player", on_delete=models.DO_NOTHING)
    second_player = models.ForeignKey(User, related_name="game_second_player", on_delete=models.DO_NOTHING)
    start_time = models.DateTimeField(auto_now_add=True)
    last_active = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, default='F', choices=GAME_STATUS_CHOICES)

    objects = GamesQuerySet.as_manager()
    def __str__(self):
        return '{0} vs {1}'.format(self.first_player, self.second_player)


class Move(models.Model):
    x = models.IntegerField()
    y = models.IntegerField()
    comment = models.CharField(max_length=100, blank=True)
    by_first_player = models.BooleanField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return 'x: {0} y: {1}'.format(self.x, self.y)

tictactoe/apps/player/models.py
from django.db import models

# Create your models here.

tictactoe/apps/main/views.py
from django.shortcuts import render, redirect
from ..gameplay.models import Game


def welcome(request):
    if request.user.is_authenticated:
        return redirect('player:home')
    else:
        all_games = Game.objects.all()
        active_games = all_games.active()
        draw_games = all_games.draw()
        return render(request,
                      template_name='main/welcome.html',
                      context={
                          'games': all_games,
                          'ngames': all_games.count(),
                          'active_games': active_games.count(),
                          'draw_games': draw_games.count(),
                      }
    )

tictactoe/apps/player/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from ..gameplay.models import Game

#user needs to be loged in to visit this page
@login_required
def home(request):
    all_my_games = Game.objects.games_for_user(request.user)
    my_active_games = all_my_games.active()
    my_draw_games = all_my_games.draw()
    return render(request=request,
                  template_name='player/home.html',
                  context={'my_games': all_my_games,
                           'my_ngames': all_my_games.count(),
                           'my_active_games': my_active_games.count(),
                           'my_draw_games': my_draw_games.count(),
                           }
                  )

tictactoe/apps/main/templates/main/welcome.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<body>
    <h1>Welcome to TikTacToe!</h1>
    <p>Total number of games in record: {{ ngames }}</p>
    <p>Total active games: {{ active_games }}</p>
    <p>Total draw games: {{ draw_games }}</p>
</body>
{% endblock %}

tictactoe/apps/player/templates/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Tic Tac Toe</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div> <!-- /container -->        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

tictactoe/apps/player/templates/player/home.html
{% extends "base.html" %}

{% block title %}
Player
{% endblock %}

{% block content %}
<body>
    <h1>Welcome, {{ user.username }}</h1>
    <h2>Your Game Status</h2>
    <p>You have {{ my_ngames }} games in record:</p>
    <ul>
        {% for g in my_games %}
        <li><strong>{{ g.status }}</strong> - Game ID {{ g.id }}: {{ g.first_player }} vs {{ g.second_player }} </li>
        {% endfor %}
    </ul>
</body>
{% endblock %}

tictactoe/apps/player/templates/player/login_form.html
{% extends "base.html" %}
{% block title %}
    Player Login
{% endblock %}
{% block content %}
<body>
    <form role="form"
          action="{% url 'player:player_login' %}"
          method="post">
        {% csrf_token %}

        <p>Please login.</p>

        {{ form }}

        <button type="submit" class="btn btn-success">Sign in</button>
    </form>
</body>
{% endblock %}

tictactoe/templates/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Tic Tac Toe</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'player:player_logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'player:player_login' %}">Login</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div> <!-- /container -->        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>